/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.vn.movieviewer.view.main;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.charset.Charset;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import javax.swing.InputVerifier;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.TableColumn;
import org.apache.commons.lang3.StringUtils;
import org.apache.log4j.Logger;
import org.vn.movieviewer.renderer.CharsetDetector;
import org.vn.movieviewer.config.GlobalVariables;
import org.vn.movieviewer.config.Utils;
import org.vn.movieviewer.controller.SmartLearningController;
import org.vn.movieviewer.renderer.PagingTable;
import org.vn.movieviewer.renderer.TableModelGeneral;
import org.vn.movieviewer.dto.SentenceDto;
import org.vn.movieviewer.renderer.CellColorRenderer;
import org.vn.movieviewer.view.dialog.SmartFilter;

/**
 *
 * @author danglph
 */
public class SubtitleCompaireFrm extends javax.swing.JFrame {

    /**
     * Creates new form SubtitleCompaireFrm
     */
    private static Logger logger = Logger.getLogger(SubtitleCompaireFrm.class);
    private PagingTable pagingTable;
    private final static int START_SENTENCE = 0;
    private final static int READ_TIME = 1;
    private final static int READ_CONTENT = 2;
    private final static int END_SENTENCE = 3;
    private final static int COLUMN_ENG = 1;
    private final static int COLUMN_VIE = 2;
    private Map<Integer, SentenceDto> mapSentenceDto = null;
    private TableModelGeneral tableModelSubtitle;

    public SubtitleCompaireFrm() {
        initComponents();
        this.setTitle("Biên tập phụ đề");
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        jTFSubEngFolderPath.setText(GlobalVariables.folderSrt);
        jTFSubEngFolderPath.setText(GlobalVariables.folderSrt + "\\2The.Little.Hours.2017.720p.BluRay.X264-AMIABLE.srt");
        jTFSubVieFolderPath.setText(GlobalVariables.folderSrt + "\\The.Little.Hours.2017.720p.BluRay.X264-AMIABLE.srt");
        String[] columnNames = {
            "Dòng", "Sub 1", "Sub 2", "Khác"
        };
        initTableListenner(columnNames);
        jTFCurrentPage.setInputVerifier(new InputVerifier() {
            @Override
            public boolean verify(JComponent input) {
                JTextField temp = (JTextField) input;
                try {
                    int number = Integer.parseInt(temp.getText());
                    if (number < PagingTable.FIRST_PAGE) {
                        JOptionPane.showMessageDialog(null, "Trang phải lớn hơn hoặc bằng " + PagingTable.FIRST_PAGE);
                        return false;
                    } else if (number > pagingTable.getTotalPage()) {
                        JOptionPane.showMessageDialog(null, "Trang phải nhỏ hơn hoặc bằng " + pagingTable.getTotalPage());
                        return false;
                    }
                    return true;
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Chỉ được nhập số!");
                }
                return false;
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTFSubEngFolderPath = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTFSubVieFolderPath = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jTFCurrentPage = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLTotalPages = new javax.swing.JLabel();
        jLDataFrom = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Chọn file");

        jTFSubEngFolderPath.setEditable(false);

        jButton5.setText("Mở thư mục");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Tải file");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Chọn file Vie");

        jTFSubVieFolderPath.setEditable(false);

        jButton7.setText("Mở thư mục");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTFSubEngFolderPath, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addComponent(jTFSubVieFolderPath))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6))
                    .addComponent(jButton5))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFSubEngFolderPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTFSubVieFolderPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7)
                    .addComponent(jButton6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTFCurrentPage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTFCurrentPage.setText("2");
        jTFCurrentPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFCurrentPageActionPerformed(evt);
            }
        });

        jButton1.setText("<");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("|<<");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText(">");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText(">>|");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLTotalPages.setText("/10");
        jLTotalPages.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLDataFrom.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLDataFrom.setText("Dữ liệu từ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFCurrentPage, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLTotalPages, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addGap(128, 128, 128)
                .addComponent(jLDataFrom, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFCurrentPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jLTotalPages, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLDataFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setCellSelectionEnabled(true);
        jScrollPane1.setViewportView(jTable1);

        jButton8.setText("Insert");

        jButton9.setText("Delete");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Save");

        jButton11.setText("Save all");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Save Eng file");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("Save Vie file");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 19, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton9)
                    .addComponent(jButton10)
                    .addComponent(jButton11)
                    .addComponent(jButton12)
                    .addComponent(jButton13)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.pagingTable.prevPage();
        initTableDataType(this.pagingTable.getRowCache(), this.pagingTable.getStart());
        Utils.updatePagingView(this.pagingTable, this.jLTotalPages, this.jLDataFrom, this.jTFCurrentPage);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (this.pagingTable.getCurentPage() != PagingTable.FIRST_PAGE) {
            this.pagingTable.setCurentPage(PagingTable.FIRST_PAGE);
            initTableDataType(this.pagingTable.getRowCache(), this.pagingTable.getStart());
            Utils.updatePagingView(this.pagingTable, this.jLTotalPages, this.jLDataFrom, this.jTFCurrentPage);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.pagingTable.nextPage();
        initTableDataType(this.pagingTable.getRowCache(), this.pagingTable.getStart());
        Utils.updatePagingView(this.pagingTable, this.jLTotalPages, this.jLDataFrom, this.jTFCurrentPage);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (this.pagingTable.getCurentPage() != this.pagingTable.getTotalPage()) {
            this.pagingTable.setCurentPage(this.pagingTable.getTotalPage());
            initTableDataType(this.pagingTable.getRowCache(), this.pagingTable.getStart());
            Utils.updatePagingView(this.pagingTable, this.jLTotalPages, this.jLDataFrom, this.jTFCurrentPage);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        openSubFolder(jTFSubEngFolderPath);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void openSubFolder(JTextField jTextField) {
        JFileChooser fc = new JFileChooser(jTextField.getText().equals("") ? "" : jTextField.getText());
        fc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Subtitle FILES", "srt", "text");
        fc.setFileFilter(filter);

        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            jTextField.setText(file.getPath());
            //This is where a real application would open the file.
            //                log.append("Opening: " + file.getName() + "." + newline);
        } else {
            //                log.append("Open command cancelled by user." + newline);
        }
    }

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:

        if (jTFSubEngFolderPath.getText().equals("") || jTFSubVieFolderPath.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Chưa có file phụ đề!!!");
            return;
        }
        loadSubEng(jTFSubEngFolderPath);
        loadSubVie(jTFSubVieFolderPath);
        
        SmartFilter smartFilter = new SmartFilter(this, true, mapSentenceDto);
        smartFilter.setLocationRelativeTo(null);
        smartFilter.setVisible(true);

        loadSubtitleMoviesFromFile(mapSentenceDto);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void loadCompairedSubs() {

    }

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        openSubFolder(jTFSubVieFolderPath);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        writeToFile(GlobalVariables.pathToSaveEngSrt, true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        /*
        1. Lấy ra những ô đã chọn cho vào mảng các dòng
        1.1 Xóa các dòng(gán giá trị "")
        2. tạo hàm tìm vị trí mới của dòng với tham số: (mảng các dòng đã chọn, vị trí dòng cũ), trả về vị trí dòng mới
        3. duyệt mapSentenceDto gọi hàm ở 2. truyền vào vị trí dòng(key), lấy ra vị trí mới(luôn lớn hơn 1 và nhỏ hơn vị trí cũ)
        4. cập nhật nội dung vào 
         */
//        getSelectedCells()
        int[] selectedColumn = this.jTable1.getSelectedColumns();
        int[] selectedRows = this.jTable1.getSelectedRows();
        if (selectedColumn.length != 1 || selectedRows.length <= 0) {
            JOptionPane.showMessageDialog(null, "Chưa chọn ô để xóa, chỉ được chọn các ô cùng 1 cột!!!");
            return;
        }
        int newPosition = 0;
        updateIndexBymapSentence(selectedRows);
        int minRow = getMinrow(selectedRows);
        boolean deleteRowEng = selectedColumn[0] == 1;//cột 1 là cột Eng, cột 2 là cột Vie

        clearValueAtDeletedRows(selectedRows, deleteRowEng);

        for (int oldPos = minRow + 1; oldPos <= mapSentenceDto.size(); oldPos++) {
            newPosition = getNewPosition(selectedRows, oldPos);
            if (newPosition > oldPos) {
                logger.error(newPosition + " ~ " + oldPos);
            } else if (newPosition == oldPos) {
                logger.debug(newPosition + " ~ " + oldPos);

                if (deleteRowEng) {
                    mapSentenceDto.get(newPosition).initContent("");
                    mapSentenceDto.get(newPosition).compaireContent();
                } else {
                    mapSentenceDto.get(newPosition).initContentTranslate("");
                    mapSentenceDto.get(newPosition).compaireContent();
                }
            } else {
                if (deleteRowEng) {
                    mapSentenceDto.get(newPosition).initContent(mapSentenceDto.get(oldPos).getContent().toString());
                    mapSentenceDto.get(newPosition).compaireContent();
//                    mapSentenceDto.get(newPosition).setContent(mapSentenceDto.get(oldPos).getContent().toString());
                } else {
                    mapSentenceDto.get(newPosition).initContentTranslate(mapSentenceDto.get(oldPos).getContentTranslate().toString());
                    mapSentenceDto.get(newPosition).compaireContent();
//                    mapSentenceDto.get(newPosition).setContentTranslate(mapSentenceDto.get(oldPos).getContentTranslate().toString());
                }
            }
        }

        if (newPosition < mapSentenceDto.size()) {
            for (int i = newPosition + 1; i <= mapSentenceDto.size(); i++) {
                if (deleteRowEng) {
                    mapSentenceDto.get(i).initContent("");
                    mapSentenceDto.get(i).compaireContent();
                } else {
                    mapSentenceDto.get(i).initContentTranslate("");
                    mapSentenceDto.get(i).compaireContent();
                }
            }
        }

        initTableDataType(this.pagingTable.getRowCache(), this.pagingTable.getStart());
        Utils.updatePagingView(this.pagingTable, this.jLTotalPages, this.jLDataFrom, this.jTFCurrentPage);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        writeToFile(GlobalVariables.pathToSaveVieSrt, false);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        writeToFile(GlobalVariables.pathToSaveEngSrt, true);
        writeToFile(GlobalVariables.pathToSaveVieSrt, false);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jTFCurrentPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFCurrentPageActionPerformed
        // TODO add your handling code here:
        try {
            this.pagingTable.setCurentPage(Integer.parseInt(jTFCurrentPage.getText()));
            initTableDataType(this.pagingTable.getRowCache(), this.pagingTable.getStart());
            Utils.updatePagingView(this.pagingTable, this.jLTotalPages, this.jLDataFrom, this.jTFCurrentPage);
        } catch (Exception e) {
            logger.error(e.getMessage(), e);
        }

    }//GEN-LAST:event_jTFCurrentPageActionPerformed

    private int getNewPosition(int[] arrSelectedRows, int oldIndex) {
        int newIndex = oldIndex;

        for (int i = arrSelectedRows.length - 1; i >= 0; i--) {
            int selectedRow = arrSelectedRows[i];
            if (oldIndex == selectedRow) {
                return oldIndex;
            } else if (oldIndex > selectedRow) {
                newIndex--;
            }
        }

        return newIndex;
    }

    private List<Integer> daoSubtitleGetIDList(Map<Integer, SentenceDto> lstSentenceDto) {
        List<Integer> lstId = new ArrayList<>();
        for (Map.Entry<Integer, SentenceDto> entry : lstSentenceDto.entrySet()) {
            Integer key = entry.getKey();
            lstId.add(key);
        }
        return lstId;
    }

    private List<SentenceDto> daoSubtitleGet(boolean b, String string, String string0, int start, int pageOffset, Map<Integer, SentenceDto> lstSentenceDto) {
        List<SentenceDto> lstSequenceInPage = new ArrayList<>();
        int startRow = start + 1;
        int endRow = Integer.min(mapSentenceDto.size() + 1, startRow + pageOffset);
        for (int i = startRow; i < endRow; i++) {
            if (!mapSentenceDto.containsKey(i)) {
                logger.debug("Stop, map size = " + mapSentenceDto.size() + "~" + i);
                break;
            }
            lstSequenceInPage.add(mapSentenceDto.get(i));
        }
        return lstSequenceInPage;
    }

    private void loadSubtitleMoviesFromFile(Map<Integer, SentenceDto> lstSentenceDto) {
        //load subtitle from file
        this.pagingTable = null;
        this.pagingTable = new PagingTable(daoSubtitleGetIDList(lstSentenceDto)) {//new ArrayList<Integer>()
//        this.pagingTable = new PagingTable(null) {//new ArrayList<Integer>()

            @Override
            public void AddPageToRowCache() {
                List<SentenceDto> lstSequenceInPage = daoSubtitleGet(true, "", "", this.getStart(), this.getPageOffset(), lstSentenceDto);
                if (this.rowCache != null) {
                    this.rowCache.clear();
                } else {
                    this.rowCache = new ArrayList<>();
                }
                for (Iterator<SentenceDto> iterator = lstSequenceInPage.iterator(); iterator.hasNext();) {
                    SentenceDto next = iterator.next();
                    this.rowCache.add(next);
                }
            }
        };
//        lstImportMovies = (List<MainMovie>)this.pagingTable.getRowCache();
        initTableDataType(this.pagingTable.getRowCache(), this.pagingTable.getStart());
        Utils.updatePagingView(this.pagingTable, this.jLTotalPages, this.jLDataFrom, this.jTFCurrentPage);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
//        System.out.print(StringUtils.isNumeric("1"));
        logger.debug(">>>>>");
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubtitleCompaireFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubtitleCompaireFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubtitleCompaireFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubtitleCompaireFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubtitleCompaireFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLDataFrom;
    private javax.swing.JLabel jLTotalPages;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFCurrentPage;
    private javax.swing.JTextField jTFSubEngFolderPath;
    private javax.swing.JTextField jTFSubVieFolderPath;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
//
//    private void updatePagingView() {
//        jLTotalPages.setText("/" + this.pagingTable.getTotalPage());
//        jTFCurrentPage.setText(this.pagingTable.getCurentPage() + "");
//        if (this.pagingTable.getTotalPage() == 0) {
//            jLDataFrom.setText("Không có dữ liệu");
//        } else {
//            jLDataFrom.setText("Dữ liệu từ " + (this.pagingTable.getStart() + 1) + " - " + this.pagingTable.getLimit() + "/" + this.pagingTable.getTotalRow());
//        }
//    }

    private void initTableDataType(List<Object> lstObject, int start) {

        this.tableModelSubtitle.getDataVector().removeAllElements();
        if (lstObject != null && !lstObject.isEmpty()) {
            Object[] moviesData = null;

            for (int i = 0; i < lstObject.size(); i++) {
                moviesData = new Object[this.tableModelSubtitle.getColumnCount()];
                SentenceDto sentenceDto = (SentenceDto) lstObject.get(i);
                moviesData[0] = sentenceDto.getRowNumber();
                moviesData[1] = sentenceDto.getContent();
                moviesData[2] = sentenceDto.getContentTranslate();
                moviesData[3] = sentenceDto.getIsDifferent();
                tableModelSubtitle.addRow(moviesData);
            }
        }
        this.jTable1.updateUI();
    }

    private void initTableListenner(String[] columnNames) {
        //init tableview

        this.tableModelSubtitle = new TableModelGeneral(columnNames) {
            @Override
            public Class<?> getColumnClass(int columnIndex) {
//           "Dòng", "Sub 1", "Sub 2", "Khác"
                Class clazz = Object.class;
                switch (columnIndex) {
//                    case 0:
//                        clazz = Boolean.class;
//                        break;
//                    case 2:
//                        clazz = StarRater.class;
//                        break;
//                    case 4:
//                        clazz = Date.class;
//                        break;
//                    case 5:
//                        clazz = ImageIcon.class;
//                        break;

                }
                return clazz;
            }

            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 1 || column == 2;
            }

            @Override
            public void setValueAt(Object value, int row, int column) {
                super.setValueAt(value, row, column);
                UpdateToMap(value, row, column);
            }
//            @Override
//            public int getRowCount() {
//                return daoMainMovie.getRowCount();
//            }
        };
//        this.tableModelSubtitle.addTableModelListener(new TableModelListenerChangeValue() {
//
//            @Override
//            public void tableChanged(TableModelEvent e) {
//                int row = e.getFirstRow();
//                int column = e.getColumn();
//                if (column > 0) {
//                    TableModelGeneral model = (TableModelGeneral) e.getSource();
//                    try {
//                        Object value = model.getValueAt(row, column);
//                        UpdateToMap(value, row, column);
//                    } catch (Exception ec) {
//                        logger.error(ec.getMessage(), ec);
//                    }
//                }
//            }
//        });
        this.jTable1.setDefaultRenderer(Object.class, new CellColorRenderer());
        this.jTable1.setModel(tableModelSubtitle);
        this.jTable1.setRowHeight(30);

        TableColumn column1 = this.jTable1.getColumnModel().getColumn(1);
        TableColumn column2 = this.jTable1.getColumnModel().getColumn(2);
        column1.setPreferredWidth(600);
        column2.setPreferredWidth(500);
        this.jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
//
//        TableColumn column1 = this.jTable1.getColumnModel().getColumn(1);
//        column1.setMinWidth(300);
//        column1.setCellRenderer(new DefaultTableCellRenderer() {
//
//            @Override
//            public Component getTableCellRendererComponent(
//                    JTable table, Object value,
//                    boolean isSelected, boolean hasFocus,
//                    int row, int column) {
//                JLabel c = (JLabel) super.getTableCellRendererComponent(table, value,
//                        isSelected, hasFocus,
//                        row, column);/// params from above 
//                int rowAfterSorted = table.convertRowIndexToModel(row);
////                Integer idMovie = (Integer)table.getModel().getValueAt(rowAfterSorted, 5);
//                MainMovie mainMovie = (MainMovie) pagingTable.getByRow(rowAfterSorted);
//                String url = mainMovie.getPosterUrl();
//                if (url == null) {
//                    url = "";
//                }
//                String html
//                        = "<html><body>"
//                        + "<img src='"
//                        //                        + "https://images-na.ssl-images-amazon.com/images/M/MV5BMzMxMTFlMDYtNjIyNS00YzQ4LWJlMDAtNGQwY2RlZGJiMmM1XkEyXkFqcGdeQXVyNzEyMTA5MTU@._V1_SY1000_SX700_AL_.jpg"
//                        + url
//                        + "'  width=240 height=320> ";
//                c.setToolTipText(html + "<br/>"
//                        + "</body></html>");
//                return c;
//            }
//        });
//        this.jTable1.setDefaultRenderer(Object.class, new CellColorRenderer());
//        this.jTable1.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
//
//            @Override
//            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
//                Component renderer = super.getTableCellRendererComponent(
//                        table, value, isSelected, hasFocus, row, column);
//
//                if ((boolean) table.getModel().getValueAt(row, 3)) {
//                    renderer.setBackground(new Color(255, 170, 198));
//                } else {
//                    renderer.setBackground(new Color(158, 234, 55));
//                }
//
//                return renderer;
//            }
//        });
    }

    private void loadSubVie(JTextField jTFSubFolderPath) {
        //Sub Eng exist and mapSentenceDto not null
        String line = null;
        try {
            File f = new File(jTFSubFolderPath.getText());
            InputStreamReader subFile = new InputStreamReader(
                    new FileInputStream(jTFSubFolderPath.getText()),
                    CharsetDetector.detectCharset(f));
            BufferedReader bufferedReader = new BufferedReader(subFile);
            if (mapSentenceDto == null) {
                JOptionPane.showMessageDialog(null, "Chưa có file phụ đề Eng!!!");
                return;
            }
            SentenceDto sentenceDto = null;
            int stateRead = START_SENTENCE;
            int rowSentence = 0;

            while ((line = bufferedReader.readLine()) != null) {
                if (line.equals("") && stateRead != READ_CONTENT) {
                    continue;
                }
                switch (stateRead) {
                    case START_SENTENCE:
                        if (StringUtils.isNumeric(line.trim()) || (sentenceDto == null)) {
                            if (sentenceDto == null) {
                                rowSentence = 1;
                            } else {
                                rowSentence = Integer.parseInt(line);
                            }
                            sentenceDto = mapSentenceDto.get(rowSentence);
                            if (sentenceDto == null) {
                                sentenceDto = new SentenceDto(rowSentence);
                                sentenceDto.setRowNumber(rowSentence);
                                mapSentenceDto.put(rowSentence, sentenceDto);
                            }
                            stateRead = READ_TIME;
                        }
                        break;
                    case READ_TIME:
                        if (line.contains(" --> ") && line.contains(":") && line.contains(",")) {
                            if(sentenceDto.getTimeString() == null || sentenceDto.getTimeString().equals("")){
                                sentenceDto.setTimeString(line);
                            }
                            stateRead = READ_CONTENT;
                        }
                        break;
                    case READ_CONTENT:
                        if (line.equals("")) {
                            sentenceDto.compaireContent();
                            stateRead = END_SENTENCE;
                            stateRead = START_SENTENCE;
//                            mapSentenceDto.put(sentenceDto.getRowNumber(), sentenceDto);
                        } else {
                            sentenceDto.setContentTranslate(sentenceDto.getContentTranslate().length() == 0 ? line
                                    : GlobalVariables.separatorBreakLine + line);
                        }
                        break;
                    case END_SENTENCE:
                        break;
                }
            }
            // Always close files.
            bufferedReader.close();
        } catch (Exception e) {
            logger.error(e.getMessage(), e);
        }
    }

    private void loadSubEng(JTextField jTFSubFolderPath) {
        String line = null;
        try {
            File f = new File(jTFSubFolderPath.getText());
            InputStreamReader subFile = new InputStreamReader(
                    new FileInputStream(jTFSubFolderPath.getText()),
                    CharsetDetector.detectCharset(f));
            BufferedReader bufferedReader = new BufferedReader(subFile);

            if (mapSentenceDto != null) {
                mapSentenceDto.clear();
            }

            if (mapSentenceDto == null) {
                mapSentenceDto = new HashMap<>();
            }
            SentenceDto sentenceDto = null;
            int stateRead = START_SENTENCE;

            while ((line = bufferedReader.readLine()) != null) {
                if (line.equals("") && stateRead != READ_CONTENT) {
                    continue;
                }
                switch (stateRead) {
                    case START_SENTENCE:
                        if (StringUtils.isNumeric(line.trim()) || (mapSentenceDto.size() == 0 && sentenceDto == null)) {
                            sentenceDto = new SentenceDto();
                            if (mapSentenceDto.size() == 0) {
                                sentenceDto.setRowNumber(1);
                            } else {
//                                if(Integer.parseInt(line) == 1508){
//                                    logger.debug(line);
//                                }
                                sentenceDto.setRowNumber(Integer.parseInt(line));
                            }
                            mapSentenceDto.put(sentenceDto.getRowNumber(), sentenceDto);
                            stateRead = READ_TIME;
                        }
                        break;
                    case READ_TIME:
                        if (line.contains(" --> ") && line.contains(":") && line.contains(",")) {
                            sentenceDto.setTimeString(line);
                            stateRead = READ_CONTENT;
                        }
                        break;
                    case READ_CONTENT:
                        if (line.equals("")) {
                            stateRead = END_SENTENCE;
                            stateRead = START_SENTENCE;
                        } else {
                            sentenceDto.setContent(sentenceDto.getContent().length() == 0 ? line
                                    : GlobalVariables.separatorBreakLine + line);
                        }
                        break;
                    case END_SENTENCE:
                        break;
                }
            }
            // Always close files.
            bufferedReader.close();
        } catch (Exception e) {
            logger.error(e.getMessage(), e);
        }
    }

    private int getMinrow(int[] selectedRows) {

        Arrays.sort(selectedRows);
        return selectedRows[0];
    }

    private void updateIndexBymapSentence(int[] selectedRows) {
        for (int i = 0; i < selectedRows.length; i++) {
            SentenceDto sentenceDto = ((SentenceDto) this.pagingTable.getByRow(selectedRows[i]));
            selectedRows[i] = sentenceDto.getRowNumber();
        }
    }

    private void clearValueAtDeletedRows(int[] selectedRows, boolean deleteRowEng) {
        for (int i = 0; i < selectedRows.length; i++) {
            SentenceDto sentenceDto = mapSentenceDto.get(selectedRows[i]);

            if (deleteRowEng) {
                SmartLearningController.learn(SmartLearningController.DELETE, sentenceDto.getContent().toString());
                sentenceDto.initContent("");
                sentenceDto.compaireContent();
            } else {
                SmartLearningController.learn(SmartLearningController.DELETE, sentenceDto.getContentTranslate().toString());
                sentenceDto.initContentTranslate("");
                sentenceDto.compaireContent();
            }
        }
    }

    private void UpdateToMap(Object value, int row, int col) {
        SentenceDto sentenceDto = (SentenceDto) this.pagingTable.getByRow(row);
        if (col == COLUMN_ENG) {
            sentenceDto.initContent(value.toString());
        } else if (col == COLUMN_VIE) {
            sentenceDto.initContentTranslate(value.toString());
        }

    }

    private void writeToFile(String pathToFile, boolean isEng) {
        Path path = Paths.get(pathToFile);
        Charset ENCODING = StandardCharsets.UTF_8;
        try {
            BufferedWriter writer = Files.newBufferedWriter(path, ENCODING);
            for (Map.Entry<Integer, SentenceDto> entry : mapSentenceDto.entrySet()) {
                Integer key = entry.getKey();
                SentenceDto value = entry.getValue();
                String saveContent = "";
                if (isEng) {
                    saveContent = value.getContent().toString().equals("") ? "" : value.getContent().toString();
                } else {
                    saveContent = value.getContentTranslate().toString().equals("") ? "" : value.getContentTranslate().toString();
                }

                if (!saveContent.equals("")) {
                    writer.write(value.getRowNumber() + "");
                    writer.newLine();
                    writer.write(value.getTimeString());
//                    try {
//                        
//                    } catch (Exception e) {
//                        logger.error(e.getMessage(), e);
//                    }
                    writer.newLine();
                    writer.write(saveContent);
                    writer.newLine();
                    writer.newLine();
                }
            }

            writer.flush();
            writer.close();
        } catch (IOException ex) {
            logger.error(ex.getMessage(), ex);
        } catch(Exception e){
            logger.error(e.getMessage(), e);
        }
    }

    public void UpdateSub(List<Integer> lstDeleteIndex) {
        
        clearValueAtDeletedRows(lstDeleteIndex.toArray(Integer.class), true);

        for (int oldPos = minRow + 1; oldPos <= mapSentenceDto.size(); oldPos++) {
            newPosition = getNewPosition(selectedRows, oldPos);
            if (newPosition > oldPos) {
                logger.error(newPosition + " ~ " + oldPos);
            } else if (newPosition == oldPos) {
                logger.debug(newPosition + " ~ " + oldPos);

                if (deleteRowEng) {
                    mapSentenceDto.get(newPosition).initContent("");
                    mapSentenceDto.get(newPosition).compaireContent();
                } else {
                    mapSentenceDto.get(newPosition).initContentTranslate("");
                    mapSentenceDto.get(newPosition).compaireContent();
                }
            } else {
                if (deleteRowEng) {
                    mapSentenceDto.get(newPosition).initContent(mapSentenceDto.get(oldPos).getContent().toString());
                    mapSentenceDto.get(newPosition).compaireContent();
//                    mapSentenceDto.get(newPosition).setContent(mapSentenceDto.get(oldPos).getContent().toString());
                } else {
                    mapSentenceDto.get(newPosition).initContentTranslate(mapSentenceDto.get(oldPos).getContentTranslate().toString());
                    mapSentenceDto.get(newPosition).compaireContent();
//                    mapSentenceDto.get(newPosition).setContentTranslate(mapSentenceDto.get(oldPos).getContentTranslate().toString());
                }
            }
        }

        if (newPosition < mapSentenceDto.size()) {
            for (int i = newPosition + 1; i <= mapSentenceDto.size(); i++) {
                if (deleteRowEng) {
                    mapSentenceDto.get(i).initContent("");
                    mapSentenceDto.get(i).compaireContent();
                } else {
                    mapSentenceDto.get(i).initContentTranslate("");
                    mapSentenceDto.get(i).compaireContent();
                }
            }
        }
    }
}
