package org.vn.movieviewer.dto;
// Generated Dec 1, 2017 10:54:07 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MainMovie generated by hbm2java
 */
@Entity
@Table(name="main_movie"
)
public class MainMovie  implements java.io.Serializable {


    @Id
    @Column(name="idmain_movie", unique=true, nullable=false)
    @GeneratedValue(strategy = GenerationType.AUTO)
     private Integer idmainMovie;
    @Column(name="name", nullable=false)
     private String name;
@Column(name="ivote")
     private Integer ivote;
@Temporal(TemporalType.TIMESTAMP)
     @Column(name="createDate", length=19)
     private Date createDate;
@Temporal(TemporalType.TIMESTAMP)
     @Column(name="updateDate", length=19)
     private Date updateDate;
@Column(name="genres")
     private String genres;
@Column(name="posterUrl")
     private String posterUrl;
@Column(name="isWatched")
     private Boolean isWatched;
@Column(name="subtitle")
     private Boolean subtitle;
@Column(name="releaseYear")
     private Integer releaseYear;
@Column(name="itotalScore")
     private Integer itotalScore;

    public MainMovie() {
    }

	
    public MainMovie(String name) {
        this.name = name;
    }
    public MainMovie(String name, Integer ivote, Date createDate, Date updateDate, String genres, String posterUrl, Boolean isWatched, Boolean subtitle, Integer releaseYear, Integer itotalScore) {
       this.name = name;
       this.ivote = ivote;
       this.createDate = createDate;
       this.updateDate = updateDate;
       this.genres = genres;
       this.posterUrl = posterUrl;
       this.isWatched = isWatched;
       this.subtitle = subtitle;
       this.releaseYear = releaseYear;
       this.itotalScore = itotalScore;
    }
   
    public Integer getIdmainMovie() {
        return this.idmainMovie;
    }
    
    public void setIdmainMovie(Integer idmainMovie) {
        this.idmainMovie = idmainMovie;
    }

    
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    public Integer getIvote() {
        return this.ivote;
    }
    
    public void setIvote(Integer ivote) {
        this.ivote = ivote;
    }

    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    
    public String getGenres() {
        return this.genres;
    }
    
    public void setGenres(String genres) {
        this.genres = genres;
    }

    
    public String getPosterUrl() {
        return this.posterUrl;
    }
    
    public void setPosterUrl(String posterUrl) {
        this.posterUrl = posterUrl;
    }

    
    public Boolean getIsWatched() {
        return this.isWatched;
    }
    
    public void setIsWatched(Boolean isWatched) {
        this.isWatched = isWatched;
    }

    
    public Boolean getSubtitle() {
        return this.subtitle;
    }
    
    public void setSubtitle(Boolean subtitle) {
        this.subtitle = subtitle;
    }

    
    public Integer getReleaseYear() {
        return this.releaseYear;
    }
    
    public void setReleaseYear(Integer releaseYear) {
        this.releaseYear = releaseYear;
    }

    
    public Integer getItotalScore() {
        return this.itotalScore;
    }
    
    public void setItotalScore(Integer itotalScore) {
        this.itotalScore = itotalScore;
    }




}


