package org.vn.movieviewer.dto;
// Generated Dec 1, 2017 10:54:07 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MainGenre generated by hbm2java
 */
@Entity
@Table(name="main_genre"
)
public class MainGenre  implements java.io.Serializable {


    @Id
    @Column(name="idmain_genre", unique=true, nullable=false)
    @GeneratedValue(strategy = GenerationType.AUTO)
     private Integer idmainGenre;
    @Column(name="name", nullable=false, length=100)
     private String name;

    public MainGenre() {
    }

    public MainGenre(String name) {
       this.name = name;
    }
   
    public Integer getIdmainGenre() {
        return this.idmainGenre;
    }
    
    public void setIdmainGenre(Integer idmainGenre) {
        this.idmainGenre = idmainGenre;
    }

    
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


