package org.vn.movieviewer.dto;
// Generated Nov 30, 2017 8:23:27 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MainAct generated by hbm2java
 */
@Entity
@Table(name="main_act"
    ,catalog="movies_db"
)
public class MainAct  implements java.io.Serializable {


     private Integer idmainAct;
     private String name;
     private Date birthday;
     private Integer gene;
     private String nickname;

    public MainAct() {
    }

	
    public MainAct(String name) {
        this.name = name;
    }
    public MainAct(String name, Date birthday, Integer gene, String nickname) {
       this.name = name;
       this.birthday = birthday;
       this.gene = gene;
       this.nickname = nickname;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idmain_act", unique=true, nullable=false)
    public Integer getIdmainAct() {
        return this.idmainAct;
    }
    
    public void setIdmainAct(Integer idmainAct) {
        this.idmainAct = idmainAct;
    }

    
    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="birthday", length=19)
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    
    @Column(name="gene")
    public Integer getGene() {
        return this.gene;
    }
    
    public void setGene(Integer gene) {
        this.gene = gene;
    }

    
    @Column(name="nickname")
    public String getNickname() {
        return this.nickname;
    }
    
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }




}


