package org.vn.movieviewer.dto;
// Generated Dec 1, 2017 10:54:07 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MainAct generated by hbm2java
 */
@Entity
@Table(name="main_act"
)
public class MainAct  implements java.io.Serializable {


    @Id
    @Column(name="idmain_act", unique=true, nullable=false)
    @GeneratedValue(strategy = GenerationType.AUTO)
     private Integer idmainAct;
    @Column(name="name", nullable=false)
     private String name;
@Temporal(TemporalType.TIMESTAMP)
     @Column(name="birthday", length=19)
     private Date birthday;
@Column(name="gene")
     private Integer gene;
@Column(name="nickname")
     private String nickname;

    public MainAct() {
    }

	
    public MainAct(String name) {
        this.name = name;
    }
    public MainAct(String name, Date birthday, Integer gene, String nickname) {
       this.name = name;
       this.birthday = birthday;
       this.gene = gene;
       this.nickname = nickname;
    }
   
    public Integer getIdmainAct() {
        return this.idmainAct;
    }
    
    public void setIdmainAct(Integer idmainAct) {
        this.idmainAct = idmainAct;
    }

    
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    
    public Integer getGene() {
        return this.gene;
    }
    
    public void setGene(Integer gene) {
        this.gene = gene;
    }

    
    public String getNickname() {
        return this.nickname;
    }
    
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }




}


