package org.vn.movieviewer.dto;
// Generated Apr 12, 2018 11:14:16 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SysPermission generated by hbm2java
 */
@Entity
@Table(name="sys_permission"
)
public class SysPermission  implements java.io.Serializable {


     private Integer idsysPermission;
     private String sysPermissionName;
     private Date dateCreate;

    public SysPermission() {
    }

	
    public SysPermission(String sysPermissionName) {
        this.sysPermissionName = sysPermissionName;
    }
    public SysPermission(String sysPermissionName, Date dateCreate) {
       this.sysPermissionName = sysPermissionName;
       this.dateCreate = dateCreate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idsys_permission", unique=true, nullable=false)
    public Integer getIdsysPermission() {
        return this.idsysPermission;
    }
    
    public void setIdsysPermission(Integer idsysPermission) {
        this.idsysPermission = idsysPermission;
    }

    
    @Column(name="sys_permission_name", nullable=false, length=45)
    public String getSysPermissionName() {
        return this.sysPermissionName;
    }
    
    public void setSysPermissionName(String sysPermissionName) {
        this.sysPermissionName = sysPermissionName;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dateCreate", length=10)
    public Date getDateCreate() {
        return this.dateCreate;
    }
    
    public void setDateCreate(Date dateCreate) {
        this.dateCreate = dateCreate;
    }




}


