package org.vn.movieviewer.dto;
// Generated Nov 30, 2017 8:23:27 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SysUser generated by hbm2java
 */
@Entity
@Table(name="sys_user"
    ,catalog="movies_db"
)
public class SysUser  implements java.io.Serializable {


     private Integer idsysUser;
     private String username;
     private String password;

    public SysUser() {
    }

    public SysUser(String username, String password) {
       this.username = username;
       this.password = password;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idsys_user", unique=true, nullable=false)
    public Integer getIdsysUser() {
        return this.idsysUser;
    }
    
    public void setIdsysUser(Integer idsysUser) {
        this.idsysUser = idsysUser;
    }

    
    @Column(name="username", nullable=false)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", nullable=false, length=45)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


